// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Channels         string
	FollowedChannels string
	Listeners        string
}{
	Channels:         "channels",
	FollowedChannels: "followed_channels",
	Listeners:        "listeners",
}
