// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testListeners(t *testing.T) {
	t.Parallel()

	query := Listeners()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testListenersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Listeners().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testListenersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Listeners().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Listeners().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testListenersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ListenerSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Listeners().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testListenersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ListenerExists(ctx, tx, o.ListenerID)
	if err != nil {
		t.Errorf("Unable to check if Listener exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ListenerExists to return true, but got false.")
	}
}

func testListenersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	listenerFound, err := FindListener(ctx, tx, o.ListenerID)
	if err != nil {
		t.Error(err)
	}

	if listenerFound == nil {
		t.Error("want a record, got nil")
	}
}

func testListenersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Listeners().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testListenersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Listeners().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testListenersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	listenerOne := &Listener{}
	listenerTwo := &Listener{}
	if err = randomize.Struct(seed, listenerOne, listenerDBTypes, false, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}
	if err = randomize.Struct(seed, listenerTwo, listenerDBTypes, false, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = listenerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = listenerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Listeners().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testListenersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	listenerOne := &Listener{}
	listenerTwo := &Listener{}
	if err = randomize.Struct(seed, listenerOne, listenerDBTypes, false, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}
	if err = randomize.Struct(seed, listenerTwo, listenerDBTypes, false, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = listenerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = listenerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Listeners().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func listenerBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Listener) error {
	*o = Listener{}
	return nil
}

func listenerAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Listener) error {
	*o = Listener{}
	return nil
}

func listenerAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Listener) error {
	*o = Listener{}
	return nil
}

func listenerBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Listener) error {
	*o = Listener{}
	return nil
}

func listenerAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Listener) error {
	*o = Listener{}
	return nil
}

func listenerBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Listener) error {
	*o = Listener{}
	return nil
}

func listenerAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Listener) error {
	*o = Listener{}
	return nil
}

func listenerBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Listener) error {
	*o = Listener{}
	return nil
}

func listenerAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Listener) error {
	*o = Listener{}
	return nil
}

func testListenersHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Listener{}
	o := &Listener{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, listenerDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Listener object: %s", err)
	}

	AddListenerHook(boil.BeforeInsertHook, listenerBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	listenerBeforeInsertHooks = []ListenerHook{}

	AddListenerHook(boil.AfterInsertHook, listenerAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	listenerAfterInsertHooks = []ListenerHook{}

	AddListenerHook(boil.AfterSelectHook, listenerAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	listenerAfterSelectHooks = []ListenerHook{}

	AddListenerHook(boil.BeforeUpdateHook, listenerBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	listenerBeforeUpdateHooks = []ListenerHook{}

	AddListenerHook(boil.AfterUpdateHook, listenerAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	listenerAfterUpdateHooks = []ListenerHook{}

	AddListenerHook(boil.BeforeDeleteHook, listenerBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	listenerBeforeDeleteHooks = []ListenerHook{}

	AddListenerHook(boil.AfterDeleteHook, listenerAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	listenerAfterDeleteHooks = []ListenerHook{}

	AddListenerHook(boil.BeforeUpsertHook, listenerBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	listenerBeforeUpsertHooks = []ListenerHook{}

	AddListenerHook(boil.AfterUpsertHook, listenerAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	listenerAfterUpsertHooks = []ListenerHook{}
}

func testListenersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Listeners().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testListenersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(listenerColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Listeners().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testListenerToManyFollowedChannels(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Listener
	var b, c FollowedChannel

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, followedChannelDBTypes, false, followedChannelColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, followedChannelDBTypes, false, followedChannelColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.ListenerID = a.ListenerID
	c.ListenerID = a.ListenerID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.FollowedChannels().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.ListenerID == b.ListenerID {
			bFound = true
		}
		if v.ListenerID == c.ListenerID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := ListenerSlice{&a}
	if err = a.L.LoadFollowedChannels(ctx, tx, false, (*[]*Listener)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FollowedChannels); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.FollowedChannels = nil
	if err = a.L.LoadFollowedChannels(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FollowedChannels); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testListenerToManyAddOpFollowedChannels(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Listener
	var b, c, d, e FollowedChannel

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, listenerDBTypes, false, strmangle.SetComplement(listenerPrimaryKeyColumns, listenerColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*FollowedChannel{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, followedChannelDBTypes, false, strmangle.SetComplement(followedChannelPrimaryKeyColumns, followedChannelColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*FollowedChannel{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddFollowedChannels(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ListenerID != first.ListenerID {
			t.Error("foreign key was wrong value", a.ListenerID, first.ListenerID)
		}
		if a.ListenerID != second.ListenerID {
			t.Error("foreign key was wrong value", a.ListenerID, second.ListenerID)
		}

		if first.R.Listener != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Listener != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.FollowedChannels[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.FollowedChannels[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.FollowedChannels().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testListenersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testListenersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ListenerSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testListenersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Listeners().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	listenerDBTypes = map[string]string{`ListenerID`: `varchar`, `Name`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`}
	_               = bytes.MinRead
)

func testListenersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(listenerPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(listenerAllColumns) == len(listenerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Listeners().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testListenersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(listenerAllColumns) == len(listenerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Listener{}
	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Listeners().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, listenerDBTypes, true, listenerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(listenerAllColumns, listenerPrimaryKeyColumns) {
		fields = listenerAllColumns
	} else {
		fields = strmangle.SetComplement(
			listenerAllColumns,
			listenerPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ListenerSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testListenersUpsert(t *testing.T) {
	t.Parallel()

	if len(listenerAllColumns) == len(listenerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLListenerUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Listener{}
	if err = randomize.Struct(seed, &o, listenerDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Listener: %s", err)
	}

	count, err := Listeners().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, listenerDBTypes, false, listenerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Listener struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Listener: %s", err)
	}

	count, err = Listeners().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
